/*******************************************************************************
   Création des bases de données SQL Server pour l'ETL
   Bases : DSA_ONLINE, ODS_ONLINE, DSA_STORE, ODS_STORE, DWH_COMMON
********************************************************************************/

-- Supprimer les bases si elles existent
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'DSA_ONLINE_LOKOUN_THYS')
BEGIN
    ALTER DATABASE [DSA_ONLINE_LOKOUN_THYS] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [DSA_ONLINE_LOKOUN_THYS];
END
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'ODS_ONLINE_LOKOUN_THYS')
BEGIN
    ALTER DATABASE [ODS_ONLINE_LOKOUN_THYS] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [ODS_ONLINE_LOKOUN_THYS];
END
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'DSA_STORE_LOKOUN_THYS')
BEGIN
    ALTER DATABASE [DSA_STORE_LOKOUN_THYS] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [DSA_STORE_LOKOUN_THYS];
END
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'ODS_STORE_LOKOUN_THYS')
BEGIN
    ALTER DATABASE [ODS_STORE_LOKOUN_THYS] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [ODS_STORE_LOKOUN_THYS];
END
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'DWH_COMMON_LOKOUN_THYS')
BEGIN
    ALTER DATABASE [DWH_COMMON_LOKOUN_THYS] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [DWH_COMMON_LOKOUN_THYS];
END
GO

-- Créer les bases
CREATE DATABASE [DSA_ONLINE_LOKOUN_THYS];
GO

CREATE DATABASE [ODS_ONLINE_LOKOUN_THYS];
GO

CREATE DATABASE [DSA_STORE_LOKOUN_THYS];
GO

CREATE DATABASE [ODS_STORE_LOKOUN_THYS];
GO

CREATE DATABASE [DWH_COMMON_LOKOUN_THYS];
GO

PRINT 'Bases de données créées avec succès : DSA_ONLINE_LOKOUN_THYS, ODS_ONLINE_LOKOUN_THYS, DSA_STORE_LOKOUN_THYS, ODS_STORE_LOKOUN_THYS, DWH_COMMON_LOKOUN_THYS';
GO
