USE [DWH_COMMON_LOKOUN_THYS] DROP TABLE IF EXISTS [dbo].[FACT_INVOICE_LINE] DROP TABLE IF EXISTS [dbo].[FACT_INVOICE] DROP TABLE IF EXISTS [dbo].[FACT_VENTES] DROP TABLE IF EXISTS [dbo].[DIM_TRACK] DROP TABLE IF EXISTS [dbo].[DIM_CUSTOMER] DROP TABLE IF EXISTS [dbo].[DIM_EMPLOYEE] DROP TABLE IF EXISTS [dbo].[DIM_CHANNEL] DROP TABLE IF EXISTS [dbo].[DIM_DATE] DROP TABLE IF EXISTS [dbo].[DIM_ALBUM] DROP TABLE IF EXISTS [dbo].[DIM_ARTIST] DROP TABLE IF EXISTS [dbo].[DIM_GENRE] DROP TABLE IF EXISTS [dbo].[DIM_MEDIATYPE] CREATE TABLE [dbo].[DIM_DATE] (
    [DATE_JOUR] DATE NOT NULL,
    [NUMERO_JOUR] INT,
    [NUMERO_MOIS] INT,
    [NOM_MOIS] NVARCHAR(10),
    [NUMERO_TRIMESTRE] INT,
    [NUMERO_ANNEE] INT,
    CONSTRAINT [PK_DIM_DATE] PRIMARY KEY CLUSTERED ([DATE_JOUR])
) CREATE TABLE [dbo].[DIM_CHANNEL] (
    [TK_CANAL] INT IDENTITY(1, 1) NOT NULL,
    [CODE_CANAL] INT NOT NULL,
    [LIBELLE] NVARCHAR(50) NOT NULL,
    [SOURCE_DONNEES] NVARCHAR(100) NOT NULL,
    [DESCRIPTION] NVARCHAR(200),
    CONSTRAINT [PK_DIM_CHANNEL] PRIMARY KEY CLUSTERED ([TK_CANAL])
)
INSERT INTO [dbo].[DIM_CHANNEL] (
        [CODE_CANAL],
        [LIBELLE],
        [SOURCE_DONNEES],
        [DESCRIPTION]
    )
VALUES (
        1,
        N'En ligne',
        N'Chinook',
        N'Base de données Chinook - Ventes en ligne'
    )
INSERT INTO [dbo].[DIM_CHANNEL] (
        [CODE_CANAL],
        [LIBELLE],
        [SOURCE_DONNEES],
        [DESCRIPTION]
    )
VALUES (
        2,
        N'Magasin physique',
        N'Magasin',
        N'Base de données Magasin - Ventes en magasin physique'
    ) CREATE TABLE [dbo].[DIM_EMPLOYEE] (
        [TK_EMPLOYE] INT IDENTITY(1, 1) NOT NULL,
        [NK_ID_EMPLOYE] INT NOT NULL,
        [NOM] NVARCHAR(20),
        [PRENOM] NVARCHAR(20),
        [FONCTION] NVARCHAR(30),
        [SUPERVISEUR_NOM_COMPLET] NVARCHAR(50),
        [DATE_NAISSANCE] DATE,
        [DATE_EMBAUCHE] DATE,
        [ADRESSE] NVARCHAR(70),
        [VILLE] NVARCHAR(40),
        [ETAT_PROVINCE] NVARCHAR(40),
        [PAYS] NVARCHAR(40),
        [CODE_POSTAL] NVARCHAR(10),
        [TELEPHONE] NVARCHAR(24),
        [EMAIL] NVARCHAR(60),
        [DATE_DEBUT] DATETIME2,
        [DATE_FIN] DATETIME2,
        CONSTRAINT [PK_DIM_EMPLOYEE] PRIMARY KEY CLUSTERED ([TK_EMPLOYE])
    ) CREATE TABLE [dbo].[DIM_CUSTOMER] (
        [TK_CLIENT] INT IDENTITY(1, 1) NOT NULL,
        [NK_ID_CLIENT] INT NOT NULL,
        [PRENOM] NVARCHAR(40),
        [NOM] NVARCHAR(20),
        [ENTREPRISE] NVARCHAR(80),
        [ADRESSE] NVARCHAR(70),
        [VILLE] NVARCHAR(40),
        [ETAT_PROVINCE] NVARCHAR(40),
        [PAYS] NVARCHAR(40),
        [CODE_POSTAL] NVARCHAR(10),
        [TELEPHONE] NVARCHAR(24),
        [EMAIL] NVARCHAR(60),
        [DATE_DEBUT] DATETIME2,
        [DATE_FIN] DATETIME2,
        CONSTRAINT [PK_DIM_CUSTOMER] PRIMARY KEY CLUSTERED ([TK_CLIENT])
    ) CREATE TABLE [dbo].[DIM_TRACK] (
        [TK_PISTE] INT IDENTITY(1, 1) NOT NULL,
        [NK_ID_PISTE] INT NOT NULL,
        [NOM_PISTE] NVARCHAR(200),
        [COMPOSER] NVARCHAR(220),
        [DURATION_MS] INT,
        [FILESIZE_BYTES] INT,
        [NOM_ALBUM] NVARCHAR(160),
        [NOM_ARTISTE] NVARCHAR(120),
        [NOM_GENRE] NVARCHAR(120),
        [NOM_TYPE_MEDIA] NVARCHAR(120),
        [UNIT_PRICE] NUMERIC(10, 2) NOT NULL,
        [DATE_DEBUT] DATETIME2 NOT NULL DEFAULT GETDATE(),
        [DATE_FIN] DATETIME2,
        [ACTIF] BIT NOT NULL DEFAULT 1,
        CONSTRAINT [PK_DIM_TRACK] PRIMARY KEY CLUSTERED ([TK_PISTE])
    ) CREATE INDEX [IX_DIM_TRACK_NK_ACTIF] ON [dbo].[DIM_TRACK] ([NK_ID_PISTE], [ACTIF]) CREATE TABLE [dbo].[FACT_VENTES] (
        [TK_LIGNE_FACTURE] INT IDENTITY(1, 1) NOT NULL,
        [TK_CLIENT] INT NOT NULL,
        [TK_EMPLOYE] INT NOT NULL,
        [DATE_ACHAT] DATE NOT NULL,
        [TK_CANAL] INT NOT NULL,
        [TK_PISTE] INT NOT NULL,
        [NK_ID_FACTURE] INT NOT NULL,
        [NK_LIGNE_FACTURE] INT NOT NULL,
        [ADRESSE_FACTURATION] NVARCHAR(70),
        [VILLE_FACTURATION] NVARCHAR(40),
        [ETAT_FACTURATION] NVARCHAR(40),
        [PAYS_FACTURATION] NVARCHAR(40),
        [CODE_POSTAL_FACTURATION] NVARCHAR(10),
        [QUANTITE] INT NOT NULL,
        [PRIX_UNITAIRE] NUMERIC(10, 2) NOT NULL,
        [TOTAL_LIGNE] NUMERIC(10, 2) NOT NULL,
        [MONTANT_TOTAL_FACTURE] NUMERIC(10, 2) NOT NULL,
        [DATE_CHARGEMENT] DATETIME2 DEFAULT GETDATE(),
        CONSTRAINT [PK_FACT_VENTES] PRIMARY KEY CLUSTERED ([TK_LIGNE_FACTURE])
    )
ALTER TABLE [dbo].[FACT_VENTES]
ADD CONSTRAINT [FK_FACT_VENTES_DIM_CUSTOMER] FOREIGN KEY ([TK_CLIENT]) REFERENCES [dbo].[DIM_CUSTOMER] ([TK_CLIENT])
ALTER TABLE [dbo].[FACT_VENTES]
ADD CONSTRAINT [FK_FACT_VENTES_DIM_EMPLOYEE] FOREIGN KEY ([TK_EMPLOYE]) REFERENCES [dbo].[DIM_EMPLOYEE] ([TK_EMPLOYE])
ALTER TABLE [dbo].[FACT_VENTES]
ADD CONSTRAINT [FK_FACT_VENTES_DIM_DATE] FOREIGN KEY ([DATE_ACHAT]) REFERENCES [dbo].[DIM_DATE] ([DATE_JOUR])
ALTER TABLE [dbo].[FACT_VENTES]
ADD CONSTRAINT [FK_FACT_VENTES_DIM_CHANNEL] FOREIGN KEY ([TK_CANAL]) REFERENCES [dbo].[DIM_CHANNEL] ([TK_CANAL])
ALTER TABLE [dbo].[FACT_VENTES]
ADD CONSTRAINT [FK_FACT_VENTES_DIM_TRACK] FOREIGN KEY ([TK_PISTE]) REFERENCES [dbo].[DIM_TRACK] ([TK_PISTE])