-- ==============================================================================
-- SCRIPT : CREATE_DWH_ORACLE_BRIDGE_11G.sql
-- DESCRIPTION : Démo Data Warehouse avec Table de Bridge (Many-to-Many)
-- CIBLE : Oracle Database 11g (Utilise des Séquences et Triggers)
-- ==============================================================================

-- 1. Nettoyage des anciens objets (Tables, Séquences, Triggers)
BEGIN
   -- Tables
   FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN ('FAIT_VENTE', 'BRIDGE_PISTE_PLAYLIST', 'DIM_PLAYLIST', 'DIM_PISTE', 'DIM_CLIENT', 'DIM_DATE')) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
   
   -- Séquences
   FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name IN ('SEQ_CLIENT', 'SEQ_PISTE', 'SEQ_PLAYLIST', 'SEQ_VENTE')) LOOP
      EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
   END LOOP;
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- 2. Création des Séquences (Standard 11g)
CREATE SEQUENCE SEQ_CLIENT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PISTE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PLAYLIST START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VENTE START WITH 1 INCREMENT BY 1;

-- 3. Création des Dimensions
-- DIM_DATE
CREATE TABLE DIM_DATE (
    TK_DATE             NUMBER(8) PRIMARY KEY,
    DATE_COMPLETE       DATE NOT NULL,
    ANNEE               NUMBER(4) NOT NULL,
    MOIS_NOM            VARCHAR2(20),
    MOIS_NUM            NUMBER(2),
    TRIMESTRE           NUMBER(1)
);

-- DIM_CLIENT
CREATE TABLE DIM_CLIENT (
    TK_CLIENT           NUMBER PRIMARY KEY,
    NK_CLIENT_ID        NUMBER NOT NULL,
    NOM                 VARCHAR2(100),
    PRENOM              VARCHAR2(100),
    PAYS                VARCHAR2(50)
);

-- DIM_PISTE (Produits)
CREATE TABLE DIM_PISTE (
    TK_PISTE            NUMBER PRIMARY KEY,
    NK_PISTE_ID         NUMBER NOT NULL,
    NOM_PISTE           VARCHAR2(200),
    ARTISTE             VARCHAR2(120),
    ALBUM               VARCHAR2(160),
    GENRE               VARCHAR2(50),
    PRIX_UNITAIRE       NUMBER(10,2)
);

-- DIM_PLAYLIST
CREATE TABLE DIM_PLAYLIST (
    TK_PLAYLIST         NUMBER PRIMARY KEY,
    NK_PLAYLIST_ID      NUMBER NOT NULL,
    NOM_PLAYLIST        VARCHAR2(120)
);

-- 4. Triggers pour l'auto-incrémentation (Simulation Identity pour 11g)
CREATE OR REPLACE TRIGGER TRG_CLIENT_BI 
BEFORE INSERT ON DIM_CLIENT FOR EACH ROW 
BEGIN IF :NEW.TK_CLIENT IS NULL THEN SELECT SEQ_CLIENT.NEXTVAL INTO :NEW.TK_CLIENT FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_PISTE_BI 
BEFORE INSERT ON DIM_PISTE FOR EACH ROW 
BEGIN IF :NEW.TK_PISTE IS NULL THEN SELECT SEQ_PISTE.NEXTVAL INTO :NEW.TK_PISTE FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_PLAYLIST_BI 
BEFORE INSERT ON DIM_PLAYLIST FOR EACH ROW 
BEGIN IF :NEW.TK_PLAYLIST IS NULL THEN SELECT SEQ_PLAYLIST.NEXTVAL INTO :NEW.TK_PLAYLIST FROM DUAL; END IF; END;
/

-- 5. Table de Bridge (BRIDGE_PISTE_PLAYLIST)
CREATE TABLE BRIDGE_PISTE_PLAYLIST (
    TK_PISTE            NUMBER NOT NULL,
    TK_PLAYLIST         NUMBER NOT NULL,
    POIDS_PONDERATION    NUMBER(5,4) DEFAULT 1.0,
    CONSTRAINT PK_BRIDGE_PISTE_PLAYL PRIMARY KEY (TK_PISTE, TK_PLAYLIST),
    CONSTRAINT FK_BRIDGE_PISTE FOREIGN KEY (TK_PISTE) REFERENCES DIM_PISTE(TK_PISTE),
    CONSTRAINT FK_BRIDGE_PLAYLIST FOREIGN KEY (TK_PLAYLIST) REFERENCES DIM_PLAYLIST(TK_PLAYLIST)
);

-- 6. Table de Faits (FAIT_VENTE)
CREATE TABLE FAIT_VENTE (
    TK_VENTE            NUMBER PRIMARY KEY,
    TK_DATE             NUMBER(8) NOT NULL,
    TK_PISTE            NUMBER NOT NULL,
    TK_CLIENT           NUMBER NOT NULL,
    QUANTITE            NUMBER DEFAULT 1,
    MONTANT_TOTAL       NUMBER(10,2),
    CONSTRAINT FK_FACT_DATE FOREIGN KEY (TK_DATE) REFERENCES DIM_DATE(TK_DATE),
    CONSTRAINT FK_FACT_PISTE FOREIGN KEY (TK_PISTE) REFERENCES DIM_PISTE(TK_PISTE),
    CONSTRAINT FK_FACT_CLIENT FOREIGN KEY (TK_CLIENT) REFERENCES DIM_CLIENT(TK_CLIENT)
);

CREATE OR REPLACE TRIGGER TRG_VENTE_BI 
BEFORE INSERT ON FAIT_VENTE FOR EACH ROW 
BEGIN IF :NEW.TK_VENTE IS NULL THEN SELECT SEQ_VENTE.NEXTVAL INTO :NEW.TK_VENTE FROM DUAL; END IF; END;
/

-- ==============================================================================
-- EXEMPLE DE REQUÊTE AVEC BRIDGE
-- ==============================================================================
/*
SELECT 
    p.NOM_PLAYLIST,
    SUM(f.MONTANT_TOTAL) as CHIFFRE_AFFAIRES
FROM FAIT_VENTE f
JOIN DIM_PISTE tr ON f.TK_PISTE = tr.TK_PISTE
JOIN BRIDGE_PISTE_PLAYLIST b ON tr.TK_PISTE = b.TK_PISTE
JOIN DIM_PLAYLIST p ON b.TK_PLAYLIST = p.TK_PLAYLIST
GROUP BY p.NOM_PLAYLIST;
*/

COMMIT;
/
